// Apply 3 patches (B, C, D) sequentially to a copy of file A, producing A+B+C+D.
// The patches were generated by `diff -u` between A and B/C/D with the A filename
// baked in. We rewrite the patches to target a real path, then apply them with
// `git apply --unsafe-paths` or with a custom applier.
//
// Strategy: load A, B, C, D into memory. Build a line-by-line "merge plan":
//  - Start with A's lines.
//  - For each diff A→X, compute the insertions/deletions and apply them to
//    A's lines, accumulating in a Map keyed by line context.
//
// Since all three diffs (A→B, A→C, A→D) are derived from A, they should not
// conflict in line numbers when applied to A. We just need to splice their
// insertions in the right place.

const fs = require('fs');
const path = require('path');

function parseDiff(text) {
  // Parse a unified diff with `--- A` and `+++ B` headers.
  // Returns array of hunks: { oldStart, oldCount, newStart, newCount, lines: [{op, text}] }
  const lines = text.split(/\r?\n/);
  let i = 0;
  const hunks = [];
  // Skip the two header lines
  while (i < lines.length && !lines[i].startsWith('@@')) i++;
  while (i < lines.length) {
    if (!lines[i].startsWith('@@')) { i++; continue; }
    const m = lines[i].match(/^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@/);
    if (!m) { i++; continue; }
    const oldStart = +m[1], oldCount = +(m[2] || 1);
    const newStart = +m[3], newCount = +(m[4] || 1);
    const block = [];
    i++;
    let oldSeen = 0, newSeen = 0;
    while (i < lines.length) {
      const l = lines[i];
      if (l.startsWith('@@') || l.startsWith('---') || l.startsWith('+++')) break;
      if (l.startsWith('+')) { block.push({op: '+', text: l.slice(1)}); newSeen++; }
      else if (l.startsWith('-')) { block.push({op: '-', text: l.slice(1)}); oldSeen++; }
      else if (l.startsWith(' ')) { block.push({op: ' ', text: l.slice(1)}); oldSeen++; newSeen++; }
      else if (l === '') { /* terminator */ break; }
      i++;
    }
    hunks.push({ oldStart, oldCount, newStart, newCount, lines: block });
  }
  return hunks;
}

function applyHunksToLines(baseLines, hunks) {
  // baseLines: array of strings (no trailing \n)
  // hunks: in order, with line numbers relative to the BASE file
  // Returns: new array of lines with all hunks applied
  // Note: if hunks overlap with prior insertions, the line numbers shift.
  // For our case (all diffs are A→B, A→C, A→D where base is A), they don't overlap.

  const result = baseLines.slice();
  let totalInserted = 0;
  for (const h of hunks) {
    const insertAt = h.oldStart - 1 + totalInserted;  // 0-indexed insert position
    const removedCount = h.lines.filter(x => x.op === '-').length;
    const addedLines = h.lines.filter(x => x.op === '+').map(x => x.text);
    // Verify: the context and removed lines match
    const expectedRemoved = h.lines.filter(x => x.op !== '+').map(x => x.text);
    const actualRemoved = result.slice(insertAt, insertAt + expectedRemoved.length);
    const matches = expectedRemoved.length === actualRemoved.length &&
      expectedRemoved.every((s, i) => s === actualRemoved[i]);
    if (!matches) {
      console.error('Hunk mismatch at oldStart', h.oldStart);
      console.error('  expected first 3:', expectedRemoved.slice(0, 3));
      console.error('  actual first 3:  ', actualRemoved.slice(0, 3));
      throw new Error('hunk does not apply cleanly');
    }
    result.splice(insertAt, expectedRemoved.length, ...addedLines);
    totalInserted += addedLines.length - expectedRemoved.length;
  }
  return result;
}

const fileA = fs.readFileSync(process.argv[2], 'utf8').replace(/\r\n/g, '\n').split('\n');
// Remove the trailing empty line that comes from the final \n
if (fileA[fileA.length - 1] === '') fileA.pop();

const diffB = fs.readFileSync(process.argv[3], 'utf8');
const diffC = fs.readFileSync(process.argv[4], 'utf8');
const diffD = fs.readFileSync(process.argv[5], 'utf8');

const hunksB = parseDiff(diffB);
const hunksC = parseDiff(diffC);
const hunksD = parseDiff(diffD);

let result = fileA;
result = applyHunksToLines(result, hunksB);
console.log('After B:', result.length, 'lines');
result = applyHunksToLines(result, hunksC);
console.log('After C:', result.length, 'lines');
result = applyHunksToLines(result, hunksD);
console.log('After D:', result.length, 'lines');

fs.writeFileSync(process.argv[2], result.join('\n') + '\n');
console.log('Wrote', process.argv[2]);
